/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyPortfolioIndexRouteImport } from './routes/My-Portfolio/index'
import { Route as MyPortfolioServicesRouteImport } from './routes/My-Portfolio/Services'
import { Route as MyPortfolioProjectsRouteImport } from './routes/My-Portfolio/Projects'

const MyPortfolioIndexRoute = MyPortfolioIndexRouteImport.update({
  id: '/My-Portfolio/',
  path: '/My-Portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPortfolioServicesRoute = MyPortfolioServicesRouteImport.update({
  id: '/My-Portfolio/Services',
  path: '/My-Portfolio/Services',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPortfolioProjectsRoute = MyPortfolioProjectsRouteImport.update({
  id: '/My-Portfolio/Projects',
  path: '/My-Portfolio/Projects',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/My-Portfolio/Projects': typeof MyPortfolioProjectsRoute
  '/My-Portfolio/Services': typeof MyPortfolioServicesRoute
  '/My-Portfolio': typeof MyPortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/My-Portfolio/Projects': typeof MyPortfolioProjectsRoute
  '/My-Portfolio/Services': typeof MyPortfolioServicesRoute
  '/My-Portfolio': typeof MyPortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/My-Portfolio/Projects': typeof MyPortfolioProjectsRoute
  '/My-Portfolio/Services': typeof MyPortfolioServicesRoute
  '/My-Portfolio/': typeof MyPortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/My-Portfolio/Projects'
    | '/My-Portfolio/Services'
    | '/My-Portfolio'
  fileRoutesByTo: FileRoutesByTo
  to: '/My-Portfolio/Projects' | '/My-Portfolio/Services' | '/My-Portfolio'
  id:
    | '__root__'
    | '/My-Portfolio/Projects'
    | '/My-Portfolio/Services'
    | '/My-Portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MyPortfolioProjectsRoute: typeof MyPortfolioProjectsRoute
  MyPortfolioServicesRoute: typeof MyPortfolioServicesRoute
  MyPortfolioIndexRoute: typeof MyPortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/My-Portfolio/': {
      id: '/My-Portfolio/'
      path: '/My-Portfolio'
      fullPath: '/My-Portfolio'
      preLoaderRoute: typeof MyPortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/My-Portfolio/Services': {
      id: '/My-Portfolio/Services'
      path: '/My-Portfolio/Services'
      fullPath: '/My-Portfolio/Services'
      preLoaderRoute: typeof MyPortfolioServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/My-Portfolio/Projects': {
      id: '/My-Portfolio/Projects'
      path: '/My-Portfolio/Projects'
      fullPath: '/My-Portfolio/Projects'
      preLoaderRoute: typeof MyPortfolioProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  MyPortfolioProjectsRoute: MyPortfolioProjectsRoute,
  MyPortfolioServicesRoute: MyPortfolioServicesRoute,
  MyPortfolioIndexRoute: MyPortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
